# Generated by Django 3.0.2 on 2020-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tag',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
