# Generated by Django 3.0.2 on 2020-08-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='-', max_length=20)),
                ('date', models.DateField()),
                ('open_stock', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('adj_close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CompanyData',
            },
        ),
    ]
