# Generated by Django 3.0.2 on 2020-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_companydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
